name: Code Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4

      # Python lint
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python linters
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install ruff bandit
      - name: Ruff (annotations in Checks)
        if: ${{ hashFiles('**/*.py') != '' }}
        run: ruff check --output-format=github .
      - name: Bandit via reviewdog (security)
        if: ${{ hashFiles('**/*.py') != '' }}
        uses: reviewdog/action-bandit@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning

      # JavaScript lint
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install ESLint if JS/TS is present
        if: ${{ hashFiles('**/*.js', '**/*.ts') != '' }}
        run: |
          npm init -y
          npm i -D eslint
          npx eslint --init --no-warn-ignored || true
      - name: ESLint via reviewdog
        if: ${{ hashFiles('**/*.js', '**/*.ts') != '' }}
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: "."

  ai-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai requests
      - name: AI review suggestions
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BASE_REF: ${{ github.base_ref }}
        run: python .github/bots/llm_reviewer.py
