name: CI

on:
  push:
  pull_request:

jobs:
  lint-type-security:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff (lint/style)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      - name: isort (import order)
        run: isort --check-only .

      - name: pydocstyle (docstrings)
        run: pydocstyle .

      - name: mypy (types, strict)
        run: mypy --hide-error-context --no-pretty --show-column-numbers --no-error-summary --strict app.py

      - name: Bandit (security)
        run: bandit -r -q -f txt -o bandit-report.txt .
        continue-on-error: false

      - name: Upload Bandit report (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.txt
